// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: settled.v1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application-defined key (e.g. user ID, transaction ID).
	// Used for O(1) lookup of the most recent entry for this entity.
	// Not included in the Merkle commitment.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Audit event payload. Opaque bytes; stored and hashed by the server.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_settled_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AppendRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AppendRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing sequence number (0-based leaf index).
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Nanoseconds since Unix epoch at which the entry was durably appended.
	TimestampNs int64 `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// SHA-256(0x00 || data) — the leaf hash committed to in the Merkle tree.
	LeafHash      []byte `protobuf:"bytes,3,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_settled_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AppendResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AppendResponse) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *AppendResponse) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_settled_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	LeafHash      []byte                 `protobuf:"bytes,5,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_settled_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Entry) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entry) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_settled_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetLatestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of most-recent entries to return. 0 is treated as 1.
	// Server caps this at an implementation-defined maximum (currently 1000);
	// requests above the cap are silently clamped.
	N             uint32 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRequest) Reset() {
	*x = GetLatestRequest{}
	mi := &file_settled_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRequest) ProtoMessage() {}

func (x *GetLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type GetLatestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Most-recent entries in newest-first order: entries[0] is the newest
	// durably-stored entry. Empty if the log has no entries yet.
	// Note: entries here reflect what is durable in storage; they may not yet
	// be sealed in the latest STH.
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Total number of entries durably stored in the log. If this is greater
	// than len(entries), the response was capped and the caller can use
	// ListEntries to page through earlier entries.
	TotalAvailable uint64 `protobuf:"varint,2,opt,name=total_available,json=totalAvailable,proto3" json:"total_available,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLatestResponse) Reset() {
	*x = GetLatestResponse{}
	mi := &file_settled_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestResponse) ProtoMessage() {}

func (x *GetLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestResponse.ProtoReflect.Descriptor instead.
func (*GetLatestResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLatestResponse) GetTotalAvailable() uint64 {
	if x != nil {
		return x.TotalAvailable
	}
	return 0
}

type SignedTreeHead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeSize      uint64                 `protobuf:"varint,1,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KeyVersion    uint32                 `protobuf:"varint,6,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTreeHead) Reset() {
	*x = SignedTreeHead{}
	mi := &file_settled_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTreeHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTreeHead) ProtoMessage() {}

func (x *SignedTreeHead) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTreeHead.ProtoReflect.Descriptor instead.
func (*SignedTreeHead) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{7}
}

func (x *SignedTreeHead) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *SignedTreeHead) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *SignedTreeHead) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *SignedTreeHead) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedTreeHead) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedTreeHead) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

type GetSthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tree_size == 0 returns the latest signed tree head.
	TreeSize      uint64 `protobuf:"varint,1,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSthRequest) Reset() {
	*x = GetSthRequest{}
	mi := &file_settled_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSthRequest) ProtoMessage() {}

func (x *GetSthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSthRequest.ProtoReflect.Descriptor instead.
func (*GetSthRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetSthRequest) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

type GetSthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sth           *SignedTreeHead        `protobuf:"bytes,1,opt,name=sth,proto3" json:"sth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSthResponse) Reset() {
	*x = GetSthResponse{}
	mi := &file_settled_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSthResponse) ProtoMessage() {}

func (x *GetSthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSthResponse.ProtoReflect.Descriptor instead.
func (*GetSthResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{9}
}

func (x *GetSthResponse) GetSth() *SignedTreeHead {
	if x != nil {
		return x.Sth
	}
	return nil
}

type InclusionProofRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// tree_size == 0 uses the latest signed tree head.
	TreeSize      uint64 `protobuf:"varint,2,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionProofRequest) Reset() {
	*x = InclusionProofRequest{}
	mi := &file_settled_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionProofRequest) ProtoMessage() {}

func (x *InclusionProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionProofRequest.ProtoReflect.Descriptor instead.
func (*InclusionProofRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{10}
}

func (x *InclusionProofRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *InclusionProofRequest) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

type InclusionProofResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	LeafIndex uint64                 `protobuf:"varint,1,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	TreeSize  uint64                 `protobuf:"varint,2,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	// O(log n) sibling hashes from leaf to root (RFC 6962 PATH).
	Proof [][]byte `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	// The STH whose root_hash the proof verifies against.
	Sth           *SignedTreeHead `protobuf:"bytes,4,opt,name=sth,proto3" json:"sth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionProofResponse) Reset() {
	*x = InclusionProofResponse{}
	mi := &file_settled_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionProofResponse) ProtoMessage() {}

func (x *InclusionProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionProofResponse.ProtoReflect.Descriptor instead.
func (*InclusionProofResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{11}
}

func (x *InclusionProofResponse) GetLeafIndex() uint64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *InclusionProofResponse) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *InclusionProofResponse) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *InclusionProofResponse) GetSth() *SignedTreeHead {
	if x != nil {
		return x.Sth
	}
	return nil
}

type ConsistencyProofRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OldSize uint64                 `protobuf:"varint,1,opt,name=old_size,json=oldSize,proto3" json:"old_size,omitempty"`
	// new_size == 0 uses the latest signed tree head.
	NewSize       uint64 `protobuf:"varint,2,opt,name=new_size,json=newSize,proto3" json:"new_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyProofRequest) Reset() {
	*x = ConsistencyProofRequest{}
	mi := &file_settled_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyProofRequest) ProtoMessage() {}

func (x *ConsistencyProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyProofRequest.ProtoReflect.Descriptor instead.
func (*ConsistencyProofRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ConsistencyProofRequest) GetOldSize() uint64 {
	if x != nil {
		return x.OldSize
	}
	return 0
}

func (x *ConsistencyProofRequest) GetNewSize() uint64 {
	if x != nil {
		return x.NewSize
	}
	return 0
}

type ConsistencyProofResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OldSize uint64                 `protobuf:"varint,1,opt,name=old_size,json=oldSize,proto3" json:"old_size,omitempty"`
	NewSize uint64                 `protobuf:"varint,2,opt,name=new_size,json=newSize,proto3" json:"new_size,omitempty"`
	// O(log n) hashes proving the old tree is a prefix of the new tree (RFC 6962 PROOF).
	Proof         [][]byte        `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
	OldSth        *SignedTreeHead `protobuf:"bytes,4,opt,name=old_sth,json=oldSth,proto3" json:"old_sth,omitempty"`
	NewSth        *SignedTreeHead `protobuf:"bytes,5,opt,name=new_sth,json=newSth,proto3" json:"new_sth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyProofResponse) Reset() {
	*x = ConsistencyProofResponse{}
	mi := &file_settled_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyProofResponse) ProtoMessage() {}

func (x *ConsistencyProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyProofResponse.ProtoReflect.Descriptor instead.
func (*ConsistencyProofResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ConsistencyProofResponse) GetOldSize() uint64 {
	if x != nil {
		return x.OldSize
	}
	return 0
}

func (x *ConsistencyProofResponse) GetNewSize() uint64 {
	if x != nil {
		return x.NewSize
	}
	return 0
}

func (x *ConsistencyProofResponse) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ConsistencyProofResponse) GetOldSth() *SignedTreeHead {
	if x != nil {
		return x.OldSth
	}
	return nil
}

func (x *ConsistencyProofResponse) GetNewSth() *SignedTreeHead {
	if x != nil {
		return x.NewSth
	}
	return nil
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If > 0, replay all entries with seq >= from_seq before streaming live ones.
	// If 0, stream only entries appended after the watch is established.
	FromSeq       uint64 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_settled_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{14}
}

func (x *WatchRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type ListEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inclusive lower bound. Ignored when cursor > 0.
	FromSeq uint64 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	// Exclusive upper bound. 0 = no upper bound (scan to end of log).
	ToSeq uint64 `protobuf:"varint,2,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`
	// Pagination cursor: resume from this seq (inclusive); 0 = use from_seq.
	Cursor uint64 `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Max entries per page. 0 treated as 50; capped at 1000.
	Limit         uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_settled_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{15}
}

func (x *ListEntriesRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *ListEntriesRequest) GetToSeq() uint64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

func (x *ListEntriesRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListEntriesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEntriesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Seq to pass as cursor in the next request. 0 = no more entries.
	NextCursor    uint64 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_settled_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{16}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

type GetByKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Resume from this sequence number (inclusive). 0 = start from the beginning.
	Cursor uint64 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Maximum entries to return per page. 0 treated as 50; capped at 1000.
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByKeyRequest) Reset() {
	*x = GetByKeyRequest{}
	mi := &file_settled_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByKeyRequest) ProtoMessage() {}

func (x *GetByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetByKeyRequest) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{17}
}

func (x *GetByKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetByKeyRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetByKeyRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetByKeyResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Seq to pass as cursor in the next request. 0 means no more entries.
	NextCursor    uint64 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByKeyResponse) Reset() {
	*x = GetByKeyResponse{}
	mi := &file_settled_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByKeyResponse) ProtoMessage() {}

func (x *GetByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settled_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetByKeyResponse) Descriptor() ([]byte, []int) {
	return file_settled_v1_proto_rawDescGZIP(), []int{18}
}

func (x *GetByKeyResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetByKeyResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

var File_settled_v1_proto protoreflect.FileDescriptor

const file_settled_v1_proto_rawDesc = "" +
	"\n" +
	"\x10settled.v1.proto\x12\n" +
	"settled.v1\"5\n" +
	"\rAppendRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"b\n" +
	"\x0eAppendResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x1b\n" +
	"\tleaf_hash\x18\x03 \x01(\fR\bleafHash\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\x7f\n" +
	"\x05Entry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\tleaf_hash\x18\x05 \x01(\fR\bleafHash\"6\n" +
	"\vGetResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.settled.v1.EntryR\x05entry\" \n" +
	"\x10GetLatestRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\rR\x01n\"i\n" +
	"\x11GetLatestResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.settled.v1.EntryR\aentries\x12'\n" +
	"\x0ftotal_available\x18\x02 \x01(\x04R\x0etotalAvailable\"\xcb\x01\n" +
	"\x0eSignedTreeHead\x12\x1b\n" +
	"\ttree_size\x18\x01 \x01(\x04R\btreeSize\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\fR\brootHash\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vkey_version\x18\x06 \x01(\rR\n" +
	"keyVersion\",\n" +
	"\rGetSthRequest\x12\x1b\n" +
	"\ttree_size\x18\x01 \x01(\x04R\btreeSize\">\n" +
	"\x0eGetSthResponse\x12,\n" +
	"\x03sth\x18\x01 \x01(\v2\x1a.settled.v1.SignedTreeHeadR\x03sth\"F\n" +
	"\x15InclusionProofRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1b\n" +
	"\ttree_size\x18\x02 \x01(\x04R\btreeSize\"\x98\x01\n" +
	"\x16InclusionProofResponse\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x01 \x01(\x04R\tleafIndex\x12\x1b\n" +
	"\ttree_size\x18\x02 \x01(\x04R\btreeSize\x12\x14\n" +
	"\x05proof\x18\x03 \x03(\fR\x05proof\x12,\n" +
	"\x03sth\x18\x04 \x01(\v2\x1a.settled.v1.SignedTreeHeadR\x03sth\"O\n" +
	"\x17ConsistencyProofRequest\x12\x19\n" +
	"\bold_size\x18\x01 \x01(\x04R\aoldSize\x12\x19\n" +
	"\bnew_size\x18\x02 \x01(\x04R\anewSize\"\xd0\x01\n" +
	"\x18ConsistencyProofResponse\x12\x19\n" +
	"\bold_size\x18\x01 \x01(\x04R\aoldSize\x12\x19\n" +
	"\bnew_size\x18\x02 \x01(\x04R\anewSize\x12\x14\n" +
	"\x05proof\x18\x03 \x03(\fR\x05proof\x123\n" +
	"\aold_sth\x18\x04 \x01(\v2\x1a.settled.v1.SignedTreeHeadR\x06oldSth\x123\n" +
	"\anew_sth\x18\x05 \x01(\v2\x1a.settled.v1.SignedTreeHeadR\x06newSth\")\n" +
	"\fWatchRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x04R\afromSeq\"t\n" +
	"\x12ListEntriesRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x04R\afromSeq\x12\x15\n" +
	"\x06to_seq\x18\x02 \x01(\x04R\x05toSeq\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"c\n" +
	"\x13ListEntriesResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.settled.v1.EntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\"Q\n" +
	"\x0fGetByKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"`\n" +
	"\x10GetByKeyResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.settled.v1.EntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor2\x97\x05\n" +
	"\n" +
	"SettledLog\x12?\n" +
	"\x06Append\x12\x19.settled.v1.AppendRequest\x1a\x1a.settled.v1.AppendResponse\x126\n" +
	"\x03Get\x12\x16.settled.v1.GetRequest\x1a\x17.settled.v1.GetResponse\x12H\n" +
	"\tGetLatest\x12\x1c.settled.v1.GetLatestRequest\x1a\x1d.settled.v1.GetLatestResponse\x126\n" +
	"\x05Watch\x12\x18.settled.v1.WatchRequest\x1a\x11.settled.v1.Entry0\x01\x12N\n" +
	"\vListEntries\x12\x1e.settled.v1.ListEntriesRequest\x1a\x1f.settled.v1.ListEntriesResponse\x12E\n" +
	"\bGetByKey\x12\x1b.settled.v1.GetByKeyRequest\x1a\x1c.settled.v1.GetByKeyResponse\x12?\n" +
	"\x06GetSth\x12\x19.settled.v1.GetSthRequest\x1a\x1a.settled.v1.GetSthResponse\x12W\n" +
	"\x0eInclusionProof\x12!.settled.v1.InclusionProofRequest\x1a\".settled.v1.InclusionProofResponse\x12]\n" +
	"\x10ConsistencyProof\x12#.settled.v1.ConsistencyProofRequest\x1a$.settled.v1.ConsistencyProofResponseB;Z9github.com/richardadalton/settled/sdks/go/client/proto;pbb\x06proto3"

var (
	file_settled_v1_proto_rawDescOnce sync.Once
	file_settled_v1_proto_rawDescData []byte
)

func file_settled_v1_proto_rawDescGZIP() []byte {
	file_settled_v1_proto_rawDescOnce.Do(func() {
		file_settled_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settled_v1_proto_rawDesc), len(file_settled_v1_proto_rawDesc)))
	})
	return file_settled_v1_proto_rawDescData
}

var file_settled_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_settled_v1_proto_goTypes = []any{
	(*AppendRequest)(nil),            // 0: settled.v1.AppendRequest
	(*AppendResponse)(nil),           // 1: settled.v1.AppendResponse
	(*GetRequest)(nil),               // 2: settled.v1.GetRequest
	(*Entry)(nil),                    // 3: settled.v1.Entry
	(*GetResponse)(nil),              // 4: settled.v1.GetResponse
	(*GetLatestRequest)(nil),         // 5: settled.v1.GetLatestRequest
	(*GetLatestResponse)(nil),        // 6: settled.v1.GetLatestResponse
	(*SignedTreeHead)(nil),           // 7: settled.v1.SignedTreeHead
	(*GetSthRequest)(nil),            // 8: settled.v1.GetSthRequest
	(*GetSthResponse)(nil),           // 9: settled.v1.GetSthResponse
	(*InclusionProofRequest)(nil),    // 10: settled.v1.InclusionProofRequest
	(*InclusionProofResponse)(nil),   // 11: settled.v1.InclusionProofResponse
	(*ConsistencyProofRequest)(nil),  // 12: settled.v1.ConsistencyProofRequest
	(*ConsistencyProofResponse)(nil), // 13: settled.v1.ConsistencyProofResponse
	(*WatchRequest)(nil),             // 14: settled.v1.WatchRequest
	(*ListEntriesRequest)(nil),       // 15: settled.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),      // 16: settled.v1.ListEntriesResponse
	(*GetByKeyRequest)(nil),          // 17: settled.v1.GetByKeyRequest
	(*GetByKeyResponse)(nil),         // 18: settled.v1.GetByKeyResponse
}
var file_settled_v1_proto_depIdxs = []int32{
	3,  // 0: settled.v1.GetResponse.entry:type_name -> settled.v1.Entry
	3,  // 1: settled.v1.GetLatestResponse.entries:type_name -> settled.v1.Entry
	7,  // 2: settled.v1.GetSthResponse.sth:type_name -> settled.v1.SignedTreeHead
	7,  // 3: settled.v1.InclusionProofResponse.sth:type_name -> settled.v1.SignedTreeHead
	7,  // 4: settled.v1.ConsistencyProofResponse.old_sth:type_name -> settled.v1.SignedTreeHead
	7,  // 5: settled.v1.ConsistencyProofResponse.new_sth:type_name -> settled.v1.SignedTreeHead
	3,  // 6: settled.v1.ListEntriesResponse.entries:type_name -> settled.v1.Entry
	3,  // 7: settled.v1.GetByKeyResponse.entries:type_name -> settled.v1.Entry
	0,  // 8: settled.v1.SettledLog.Append:input_type -> settled.v1.AppendRequest
	2,  // 9: settled.v1.SettledLog.Get:input_type -> settled.v1.GetRequest
	5,  // 10: settled.v1.SettledLog.GetLatest:input_type -> settled.v1.GetLatestRequest
	14, // 11: settled.v1.SettledLog.Watch:input_type -> settled.v1.WatchRequest
	15, // 12: settled.v1.SettledLog.ListEntries:input_type -> settled.v1.ListEntriesRequest
	17, // 13: settled.v1.SettledLog.GetByKey:input_type -> settled.v1.GetByKeyRequest
	8,  // 14: settled.v1.SettledLog.GetSth:input_type -> settled.v1.GetSthRequest
	10, // 15: settled.v1.SettledLog.InclusionProof:input_type -> settled.v1.InclusionProofRequest
	12, // 16: settled.v1.SettledLog.ConsistencyProof:input_type -> settled.v1.ConsistencyProofRequest
	1,  // 17: settled.v1.SettledLog.Append:output_type -> settled.v1.AppendResponse
	4,  // 18: settled.v1.SettledLog.Get:output_type -> settled.v1.GetResponse
	6,  // 19: settled.v1.SettledLog.GetLatest:output_type -> settled.v1.GetLatestResponse
	3,  // 20: settled.v1.SettledLog.Watch:output_type -> settled.v1.Entry
	16, // 21: settled.v1.SettledLog.ListEntries:output_type -> settled.v1.ListEntriesResponse
	18, // 22: settled.v1.SettledLog.GetByKey:output_type -> settled.v1.GetByKeyResponse
	9,  // 23: settled.v1.SettledLog.GetSth:output_type -> settled.v1.GetSthResponse
	11, // 24: settled.v1.SettledLog.InclusionProof:output_type -> settled.v1.InclusionProofResponse
	13, // 25: settled.v1.SettledLog.ConsistencyProof:output_type -> settled.v1.ConsistencyProofResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_settled_v1_proto_init() }
func file_settled_v1_proto_init() {
	if File_settled_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settled_v1_proto_rawDesc), len(file_settled_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settled_v1_proto_goTypes,
		DependencyIndexes: file_settled_v1_proto_depIdxs,
		MessageInfos:      file_settled_v1_proto_msgTypes,
	}.Build()
	File_settled_v1_proto = out.File
	file_settled_v1_proto_goTypes = nil
	file_settled_v1_proto_depIdxs = nil
}
