// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: settled.v1.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettledLog_Append_FullMethodName           = "/settled.v1.SettledLog/Append"
	SettledLog_Get_FullMethodName              = "/settled.v1.SettledLog/Get"
	SettledLog_BatchAppend_FullMethodName      = "/settled.v1.SettledLog/BatchAppend"
	SettledLog_GetLatest_FullMethodName        = "/settled.v1.SettledLog/GetLatest"
	SettledLog_Watch_FullMethodName            = "/settled.v1.SettledLog/Watch"
	SettledLog_ListEntries_FullMethodName      = "/settled.v1.SettledLog/ListEntries"
	SettledLog_GetByKey_FullMethodName         = "/settled.v1.SettledLog/GetByKey"
	SettledLog_GetSth_FullMethodName           = "/settled.v1.SettledLog/GetSth"
	SettledLog_InclusionProof_FullMethodName   = "/settled.v1.SettledLog/InclusionProof"
	SettledLog_ConsistencyProof_FullMethodName = "/settled.v1.SettledLog/ConsistencyProof"
)

// SettledLogClient is the client API for SettledLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettledLogClient interface {
	// Append a new audit entry. Returns the assigned sequence number and leaf hash.
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Retrieve a single entry by sequence number.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Append multiple entries atomically: all seqs are assigned contiguously and
	// written to the WAL in a single batch. Returns one AppendResponse per entry
	// in the same order. Capped at 1000 entries per call.
	BatchAppend(ctx context.Context, in *BatchAppendRequest, opts ...grpc.CallOption) (*BatchAppendResponse, error)
	// Retrieve the most-recent N entries (newest first). n == 0 is treated as 1.
	// Returns durably-stored entries; they may not yet be sealed in the latest STH.
	GetLatest(ctx context.Context, in *GetLatestRequest, opts ...grpc.CallOption) (*GetLatestResponse, error)
	// Stream entries as they are appended. from_seq > 0 replays history first,
	// then continues live. from_seq == 0 streams only future appends.
	// The stream stays open until the client cancels it.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error)
	// Retrieve a seq-ordered page of entries within [from_seq, to_seq).
	// cursor overrides from_seq for subsequent pages; next_cursor == 0 means done.
	ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error)
	// Retrieve all entries for a given key, newest-to-oldest within the log, with
	// cursor-based pagination. cursor == 0 starts from the beginning of the log.
	// next_cursor == 0 in the response means no further pages exist.
	GetByKey(ctx context.Context, in *GetByKeyRequest, opts ...grpc.CallOption) (*GetByKeyResponse, error)
	// Retrieve a Signed Tree Head. tree_size == 0 returns the latest.
	GetSth(ctx context.Context, in *GetSthRequest, opts ...grpc.CallOption) (*GetSthResponse, error)
	// Return an inclusion proof for a given entry against a tree size.
	InclusionProof(ctx context.Context, in *InclusionProofRequest, opts ...grpc.CallOption) (*InclusionProofResponse, error)
	// Return a consistency proof between two tree sizes.
	ConsistencyProof(ctx context.Context, in *ConsistencyProofRequest, opts ...grpc.CallOption) (*ConsistencyProofResponse, error)
}

type settledLogClient struct {
	cc grpc.ClientConnInterface
}

func NewSettledLogClient(cc grpc.ClientConnInterface) SettledLogClient {
	return &settledLogClient{cc}
}

func (c *settledLogClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, SettledLog_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, SettledLog_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) BatchAppend(ctx context.Context, in *BatchAppendRequest, opts ...grpc.CallOption) (*BatchAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchAppendResponse)
	err := c.cc.Invoke(ctx, SettledLog_BatchAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) GetLatest(ctx context.Context, in *GetLatestRequest, opts ...grpc.CallOption) (*GetLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestResponse)
	err := c.cc.Invoke(ctx, SettledLog_GetLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SettledLog_ServiceDesc.Streams[0], SettledLog_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Entry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SettledLog_WatchClient = grpc.ServerStreamingClient[Entry]

func (c *settledLogClient) ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntriesResponse)
	err := c.cc.Invoke(ctx, SettledLog_ListEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) GetByKey(ctx context.Context, in *GetByKeyRequest, opts ...grpc.CallOption) (*GetByKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByKeyResponse)
	err := c.cc.Invoke(ctx, SettledLog_GetByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) GetSth(ctx context.Context, in *GetSthRequest, opts ...grpc.CallOption) (*GetSthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSthResponse)
	err := c.cc.Invoke(ctx, SettledLog_GetSth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) InclusionProof(ctx context.Context, in *InclusionProofRequest, opts ...grpc.CallOption) (*InclusionProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InclusionProofResponse)
	err := c.cc.Invoke(ctx, SettledLog_InclusionProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settledLogClient) ConsistencyProof(ctx context.Context, in *ConsistencyProofRequest, opts ...grpc.CallOption) (*ConsistencyProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsistencyProofResponse)
	err := c.cc.Invoke(ctx, SettledLog_ConsistencyProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettledLogServer is the server API for SettledLog service.
// All implementations must embed UnimplementedSettledLogServer
// for forward compatibility.
type SettledLogServer interface {
	// Append a new audit entry. Returns the assigned sequence number and leaf hash.
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Retrieve a single entry by sequence number.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Append multiple entries atomically: all seqs are assigned contiguously and
	// written to the WAL in a single batch. Returns one AppendResponse per entry
	// in the same order. Capped at 1000 entries per call.
	BatchAppend(context.Context, *BatchAppendRequest) (*BatchAppendResponse, error)
	// Retrieve the most-recent N entries (newest first). n == 0 is treated as 1.
	// Returns durably-stored entries; they may not yet be sealed in the latest STH.
	GetLatest(context.Context, *GetLatestRequest) (*GetLatestResponse, error)
	// Stream entries as they are appended. from_seq > 0 replays history first,
	// then continues live. from_seq == 0 streams only future appends.
	// The stream stays open until the client cancels it.
	Watch(*WatchRequest, grpc.ServerStreamingServer[Entry]) error
	// Retrieve a seq-ordered page of entries within [from_seq, to_seq).
	// cursor overrides from_seq for subsequent pages; next_cursor == 0 means done.
	ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error)
	// Retrieve all entries for a given key, newest-to-oldest within the log, with
	// cursor-based pagination. cursor == 0 starts from the beginning of the log.
	// next_cursor == 0 in the response means no further pages exist.
	GetByKey(context.Context, *GetByKeyRequest) (*GetByKeyResponse, error)
	// Retrieve a Signed Tree Head. tree_size == 0 returns the latest.
	GetSth(context.Context, *GetSthRequest) (*GetSthResponse, error)
	// Return an inclusion proof for a given entry against a tree size.
	InclusionProof(context.Context, *InclusionProofRequest) (*InclusionProofResponse, error)
	// Return a consistency proof between two tree sizes.
	ConsistencyProof(context.Context, *ConsistencyProofRequest) (*ConsistencyProofResponse, error)
	mustEmbedUnimplementedSettledLogServer()
}

// UnimplementedSettledLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettledLogServer struct{}

func (UnimplementedSettledLogServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedSettledLogServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSettledLogServer) BatchAppend(context.Context, *BatchAppendRequest) (*BatchAppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchAppend not implemented")
}
func (UnimplementedSettledLogServer) GetLatest(context.Context, *GetLatestRequest) (*GetLatestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatest not implemented")
}
func (UnimplementedSettledLogServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Entry]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSettledLogServer) ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntries not implemented")
}
func (UnimplementedSettledLogServer) GetByKey(context.Context, *GetByKeyRequest) (*GetByKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByKey not implemented")
}
func (UnimplementedSettledLogServer) GetSth(context.Context, *GetSthRequest) (*GetSthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSth not implemented")
}
func (UnimplementedSettledLogServer) InclusionProof(context.Context, *InclusionProofRequest) (*InclusionProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InclusionProof not implemented")
}
func (UnimplementedSettledLogServer) ConsistencyProof(context.Context, *ConsistencyProofRequest) (*ConsistencyProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsistencyProof not implemented")
}
func (UnimplementedSettledLogServer) mustEmbedUnimplementedSettledLogServer() {}
func (UnimplementedSettledLogServer) testEmbeddedByValue()                    {}

// UnsafeSettledLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettledLogServer will
// result in compilation errors.
type UnsafeSettledLogServer interface {
	mustEmbedUnimplementedSettledLogServer()
}

func RegisterSettledLogServer(s grpc.ServiceRegistrar, srv SettledLogServer) {
	// If the following call panics, it indicates UnimplementedSettledLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettledLog_ServiceDesc, srv)
}

func _SettledLog_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_BatchAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).BatchAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_BatchAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).BatchAppend(ctx, req.(*BatchAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_GetLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).GetLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_GetLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).GetLatest(ctx, req.(*GetLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SettledLogServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Entry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SettledLog_WatchServer = grpc.ServerStreamingServer[Entry]

func _SettledLog_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_ListEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).ListEntries(ctx, req.(*ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_GetByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).GetByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_GetByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).GetByKey(ctx, req.(*GetByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_GetSth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).GetSth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_GetSth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).GetSth(ctx, req.(*GetSthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_InclusionProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InclusionProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).InclusionProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_InclusionProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).InclusionProof(ctx, req.(*InclusionProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettledLog_ConsistencyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsistencyProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettledLogServer).ConsistencyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettledLog_ConsistencyProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettledLogServer).ConsistencyProof(ctx, req.(*ConsistencyProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettledLog_ServiceDesc is the grpc.ServiceDesc for SettledLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettledLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settled.v1.SettledLog",
	HandlerType: (*SettledLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _SettledLog_Append_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SettledLog_Get_Handler,
		},
		{
			MethodName: "BatchAppend",
			Handler:    _SettledLog_BatchAppend_Handler,
		},
		{
			MethodName: "GetLatest",
			Handler:    _SettledLog_GetLatest_Handler,
		},
		{
			MethodName: "ListEntries",
			Handler:    _SettledLog_ListEntries_Handler,
		},
		{
			MethodName: "GetByKey",
			Handler:    _SettledLog_GetByKey_Handler,
		},
		{
			MethodName: "GetSth",
			Handler:    _SettledLog_GetSth_Handler,
		},
		{
			MethodName: "InclusionProof",
			Handler:    _SettledLog_InclusionProof_Handler,
		},
		{
			MethodName: "ConsistencyProof",
			Handler:    _SettledLog_ConsistencyProof_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SettledLog_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "settled.v1.proto",
}
