# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from settled.proto import settled_v1_pb2 as settled_dot_proto_dot_settled__v1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in settled/proto/settled_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SettledLogStub(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/settled.v1.SettledLog/Append',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.AppendRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/settled.v1.SettledLog/Get',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.GetRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetResponse.FromString,
                _registered_method=True)
        self.GetLatest = channel.unary_unary(
                '/settled.v1.SettledLog/GetLatest',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.GetLatestRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetLatestResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/settled.v1.SettledLog/Watch',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.WatchRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.Entry.FromString,
                _registered_method=True)
        self.ListEntries = channel.unary_unary(
                '/settled.v1.SettledLog/ListEntries',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.ListEntriesRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.ListEntriesResponse.FromString,
                _registered_method=True)
        self.GetByKey = channel.unary_unary(
                '/settled.v1.SettledLog/GetByKey',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.GetByKeyRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetByKeyResponse.FromString,
                _registered_method=True)
        self.GetSth = channel.unary_unary(
                '/settled.v1.SettledLog/GetSth',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.GetSthRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetSthResponse.FromString,
                _registered_method=True)
        self.InclusionProof = channel.unary_unary(
                '/settled.v1.SettledLog/InclusionProof',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.InclusionProofRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.InclusionProofResponse.FromString,
                _registered_method=True)
        self.ConsistencyProof = channel.unary_unary(
                '/settled.v1.SettledLog/ConsistencyProof',
                request_serializer=settled_dot_proto_dot_settled__v1__pb2.ConsistencyProofRequest.SerializeToString,
                response_deserializer=settled_dot_proto_dot_settled__v1__pb2.ConsistencyProofResponse.FromString,
                _registered_method=True)


class SettledLogServicer(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def Append(self, request, context):
        """Append a new audit entry. Returns the assigned sequence number and leaf hash.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Retrieve a single entry by sequence number.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatest(self, request, context):
        """Retrieve the most-recent N entries (newest first). n == 0 is treated as 1.
        Returns durably-stored entries; they may not yet be sealed in the latest STH.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Stream entries as they are appended. from_seq > 0 replays history first,
        then continues live. from_seq == 0 streams only future appends.
        The stream stays open until the client cancels it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntries(self, request, context):
        """Retrieve a seq-ordered page of entries within [from_seq, to_seq).
        cursor overrides from_seq for subsequent pages; next_cursor == 0 means done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByKey(self, request, context):
        """Retrieve all entries for a given key, newest-to-oldest within the log, with
        cursor-based pagination. cursor == 0 starts from the beginning of the log.
        next_cursor == 0 in the response means no further pages exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSth(self, request, context):
        """Retrieve a Signed Tree Head. tree_size == 0 returns the latest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InclusionProof(self, request, context):
        """Return an inclusion proof for a given entry against a tree size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsistencyProof(self, request, context):
        """Return a consistency proof between two tree sizes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettledLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.AppendRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.AppendResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.GetResponse.SerializeToString,
            ),
            'GetLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatest,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetLatestRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.GetLatestResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.WatchRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.Entry.SerializeToString,
            ),
            'ListEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntries,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.ListEntriesRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.ListEntriesResponse.SerializeToString,
            ),
            'GetByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByKey,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetByKeyRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.GetByKeyResponse.SerializeToString,
            ),
            'GetSth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSth,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.GetSthRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.GetSthResponse.SerializeToString,
            ),
            'InclusionProof': grpc.unary_unary_rpc_method_handler(
                    servicer.InclusionProof,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.InclusionProofRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.InclusionProofResponse.SerializeToString,
            ),
            'ConsistencyProof': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsistencyProof,
                    request_deserializer=settled_dot_proto_dot_settled__v1__pb2.ConsistencyProofRequest.FromString,
                    response_serializer=settled_dot_proto_dot_settled__v1__pb2.ConsistencyProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'settled.v1.SettledLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('settled.v1.SettledLog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SettledLog(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/Append',
            settled_dot_proto_dot_settled__v1__pb2.AppendRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/Get',
            settled_dot_proto_dot_settled__v1__pb2.GetRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/GetLatest',
            settled_dot_proto_dot_settled__v1__pb2.GetLatestRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.GetLatestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/settled.v1.SettledLog/Watch',
            settled_dot_proto_dot_settled__v1__pb2.WatchRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.Entry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/ListEntries',
            settled_dot_proto_dot_settled__v1__pb2.ListEntriesRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.ListEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/GetByKey',
            settled_dot_proto_dot_settled__v1__pb2.GetByKeyRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.GetByKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/GetSth',
            settled_dot_proto_dot_settled__v1__pb2.GetSthRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.GetSthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InclusionProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/InclusionProof',
            settled_dot_proto_dot_settled__v1__pb2.InclusionProofRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.InclusionProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsistencyProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/ConsistencyProof',
            settled_dot_proto_dot_settled__v1__pb2.ConsistencyProofRequest.SerializeToString,
            settled_dot_proto_dot_settled__v1__pb2.ConsistencyProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
