# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from settled.proto import settled_v1_pb2 as settled_dot_v1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in settled.v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SettledLogStub(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/settled.v1.SettledLog/Append',
                request_serializer=settled_dot_v1__pb2.AppendRequest.SerializeToString,
                response_deserializer=settled_dot_v1__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/settled.v1.SettledLog/Get',
                request_serializer=settled_dot_v1__pb2.GetRequest.SerializeToString,
                response_deserializer=settled_dot_v1__pb2.GetResponse.FromString,
                _registered_method=True)
        self.GetSth = channel.unary_unary(
                '/settled.v1.SettledLog/GetSth',
                request_serializer=settled_dot_v1__pb2.GetSthRequest.SerializeToString,
                response_deserializer=settled_dot_v1__pb2.GetSthResponse.FromString,
                _registered_method=True)
        self.InclusionProof = channel.unary_unary(
                '/settled.v1.SettledLog/InclusionProof',
                request_serializer=settled_dot_v1__pb2.InclusionProofRequest.SerializeToString,
                response_deserializer=settled_dot_v1__pb2.InclusionProofResponse.FromString,
                _registered_method=True)
        self.ConsistencyProof = channel.unary_unary(
                '/settled.v1.SettledLog/ConsistencyProof',
                request_serializer=settled_dot_v1__pb2.ConsistencyProofRequest.SerializeToString,
                response_deserializer=settled_dot_v1__pb2.ConsistencyProofResponse.FromString,
                _registered_method=True)


class SettledLogServicer(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def Append(self, request, context):
        """Append a new audit entry. Returns the assigned sequence number and leaf hash.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Retrieve a single entry by sequence number.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSth(self, request, context):
        """Retrieve a Signed Tree Head. tree_size == 0 returns the latest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InclusionProof(self, request, context):
        """Return an inclusion proof for a given entry against a tree size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsistencyProof(self, request, context):
        """Return a consistency proof between two tree sizes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettledLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=settled_dot_v1__pb2.AppendRequest.FromString,
                    response_serializer=settled_dot_v1__pb2.AppendResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=settled_dot_v1__pb2.GetRequest.FromString,
                    response_serializer=settled_dot_v1__pb2.GetResponse.SerializeToString,
            ),
            'GetSth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSth,
                    request_deserializer=settled_dot_v1__pb2.GetSthRequest.FromString,
                    response_serializer=settled_dot_v1__pb2.GetSthResponse.SerializeToString,
            ),
            'InclusionProof': grpc.unary_unary_rpc_method_handler(
                    servicer.InclusionProof,
                    request_deserializer=settled_dot_v1__pb2.InclusionProofRequest.FromString,
                    response_serializer=settled_dot_v1__pb2.InclusionProofResponse.SerializeToString,
            ),
            'ConsistencyProof': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsistencyProof,
                    request_deserializer=settled_dot_v1__pb2.ConsistencyProofRequest.FromString,
                    response_serializer=settled_dot_v1__pb2.ConsistencyProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'settled.v1.SettledLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('settled.v1.SettledLog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SettledLog(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/Append',
            settled_dot_v1__pb2.AppendRequest.SerializeToString,
            settled_dot_v1__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/Get',
            settled_dot_v1__pb2.GetRequest.SerializeToString,
            settled_dot_v1__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/GetSth',
            settled_dot_v1__pb2.GetSthRequest.SerializeToString,
            settled_dot_v1__pb2.GetSthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InclusionProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/InclusionProof',
            settled_dot_v1__pb2.InclusionProofRequest.SerializeToString,
            settled_dot_v1__pb2.InclusionProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsistencyProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/settled.v1.SettledLog/ConsistencyProof',
            settled_dot_v1__pb2.ConsistencyProofRequest.SerializeToString,
            settled_dot_v1__pb2.ConsistencyProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
